# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea9cc3cb170203e0900db2d6aa36f334e1ad0c14c36c13f09ac1944a782cad63fac515e6e5ab13ee8d1bd30839c143e7f6c2b5c696d22b32b5b44134bed285fe

test:
  secret_key_base: 899deff03eb3e2d7f91533d72083b329fcced7b43d533d4049486d45830bc78e50b485bd282ef1119d14f2131d5976fcda2de7902085eea759e30a554dbc5ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
